name: Run bot

on:
  schedule:
   - cron: "1 */5 * * *"
  workflow_dispatch:

#concurrency:
#  group: ${{ github.ref }}
#  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Stockfish
        run: |
          sudo apt install build-essential
          cd ./src
          make build ARCH=x68-64
          cd ..
          mv -f ./src/stockfish engines/stockfish

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
 

      - name: Install Stockfish
        run: |
          curl -sSL https://raw.githubusercontent.com/ppigazzini/stockfish-downloader/main/posix_helper.sh | sh -s
          tar -xf stockfish-*.tar
          rm stockfish-*.tar
          mv -f stockfish/stockfish-* engines/stockfish
          rm -r stockfish

      - name: Give perms to execute engines
        run: |
          chmod +x ./engines/stockfish


      - name: Replace token
        run: |
          sed -i 's|BOT_TOKEN|${{ secrets.BOT_TOKEN }}|g' config.yml

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
        run: python user_interface.py
