name: Run bot

on:
  schedule:
   - cron: "1 */5 * * *"
  workflow_dispatch:

#concurrency:
#  group: ${{ github.ref }}
#  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Replace token
        shell: powershell
        run: |
          $yamlFilePath = "config.yml"
          $searchString = "BOT_TOKEN"
          $secretValue = "${{ secrets.BOT_TOKEN }}"
          $fileContent = Get-Content $yamlFilePath
          $newContent = $fileContent -replace $searchString, $secretValue
          Set-Content $yamlFilePath -Value $newContent

        
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
        run: python user_interface.py --upgrade
